export const APP_CONFIG = {
  brand: {
    name: "CCS Talks",
    tagline: "A modern forum for the OLFU-CCS community.",
    org: "GROUP 4™",
  },
  landing: {
    heroSubtitle: "Announcements, threads, study circles, and community events—fast, searchable, and beautifully organized.",
    stats: [
      { k: "Members", v: "2.3k" },
      { k: "Threads", v: "18k" },
      { k: "Active today", v: "312" },
    ],
    featureCards: [
      { title: "Categories", body: "Academics, events, tech, and student life—everything has a place.", icon: "🗂️" },
      { title: "Smart search", body: "Find the exact thread in seconds. Pin, bookmark, and track topics.", icon: "🔎" },
      { title: "Profiles", body: "Badges, timeline posts, and community presence—like a campus feed.", icon: "🪪" },
    ],
    community: {
      orgs: [
        { name: "CCS Dev Guild", kind: "Org", members: 312, body: "Weekly build nights, code reviews, and shipping student projects. Open to all years.", color: "#9b0028", accent: "#ff6080", tags: ["Web", "Mobile", "OpenSource"] },
        { name: "Hack Club Antipolo", kind: "Org", members: 184, body: "Hackathon training, CTF practice, and mentorship for first-time competitors.", color: "#5a0030", accent: "#ff3a6e", tags: ["Hackathon", "Security", "Mentorship"] },
        { name: "Capstone Circle", kind: "Circle", members: 96, body: "Thesis-stage students sharing scope, panel feedback, and survival stories.", color: "#3a0014", accent: "#ffb0bd", tags: ["Capstone", "Research"] },
        { name: "Study Lounge", kind: "Circle", members: 540, body: "Subject-specific study rooms — CMSC 142, automata, DSA, and beyond.", color: "#7a0024", accent: "#ff96a6", tags: ["Academics", "Reviewers"] },
      ],
      events: [
        { title: "CCS Night 2025", when: "Nov 22", where: "OLFU Antipolo Auditorium", body: "Annual showcase, awards, and the org talent night." },
        { title: "Code & Coffee", when: "Every Friday", where: "Library 3F", body: "Casual jam — bring a laptop, leave with a PR." },
        { title: "Capstone Clinic", when: "Oct 12", where: "CCS Faculty Room", body: "Open table feedback for thesis groups." },
      ],
    },
    footer: {
      columns: [
        { title: "Product", links: ["Forum", "Profiles", "Bookmarks", "Subscriptions"] },
        { title: "Community", links: ["Events", "Study groups", "Guidelines", "Support"] },
        { title: "Build", links: ["Roadmap", "Changelog", "Feedback", "Credits"] },
      ],
      copyright: "© 2026 CCS Talks",
    },
  },
  routes: {
    landing: { title: "Home" },
    about: { title: "About" },
    forum: { title: "Forum" },
    profile: { title: "Profile" },
    timeline: { title: "My timeline" },
    activities: { title: "Activities" },
    search: { title: "Search" },
    bookmarks: { title: "Bookmarks" },
    friends: { title: "Friends" },
    subs: { title: "Subscriptions" },
    settings: { title: "Settings" },
    login: { title: "Sign in" },
    register: { title: "Sign up" },
  },
  nav: {
    top: ["about", "forum", "login"],
    sidebarPrimary: [
      { key: "forum", icon: "🏠", label: "Home" },
      { key: "search", icon: "🔎", label: "Search" },
      { key: "profile", icon: "👤", label: "Profile" },
      { key: "activities", icon: "🧾", label: "Activities" },
      { key: "bookmarks", icon: "🔖", label: "Bookmarks" },
      { key: "friends", icon: "👥", label: "Friends" },
      { key: "subs", icon: "＋", label: "Subscriptions" },
    ],
    sidebarSecondary: [
      { key: "settings", icon: "⚙️", label: "Settings" },
      { key: "landing", icon: "↩", label: "Sign out" },
    ],
  },
  placeholders: {
    composer: "What's on your mind?",
    search: "Search...",
    landingCta: "Join us.",
  },
};

export const DEFAULT_PROFILE = {
  id: "u_you",
  name: "Juan Dela Cruz",
  handle: "juandc",
  status: "Student",
  university: "Our Lady of Fatima University",
  college: "College of Computer Studies",
  program: "BS Computer Science",
  year: "3rd Year",
  campus: "Antipolo",
  focus: "HCI",
  org: "CCS Dev Guild",
  bio: "Computer science student building expressive UI systems. Interests: UX engineering, realtime graphics, and app polish.",
  badges: ["Dean’s Lister", "Hackathon ’25", "Org Member"],
  // --- visual identity (editable) ---
  avatarColor: "#9b0028",
  avatarAccent: "#ff6080",
  bannerColor: "#3a0014",
  bannerAccent: "#ff3a6e",
};

export const MOCK_USERS = {
  u_renz: {
    id: "u_renz",
    name: "Renz Delos Santos",
    handle: "renz_ds",
    status: "Student",
    university: "OLFU",
    college: "CCS",
    program: "BSIT",
    year: "4th Year",
    campus: "Antipolo",
    focus: "Full-stack",
    org: "Capstone Team",
    bio: "Shipped projects, survived finals, and still here to help the community.",
    badges: ["Capstone ’26", "Volunteer"],
  },
  u_maica: {
    id: "u_maica",
    name: "Maica Villanueva",
    handle: "maica_v",
    status: "Student",
    university: "OLFU",
    college: "CCS",
    program: "BSCS",
    year: "3rd Year",
    campus: "Antipolo",
    focus: "Theory",
    org: "Study Circle",
    bio: "Automata enjoyer. Coffee powered. Ask me about CMSC 142.",
    badges: ["Study Group Lead"],
  },
  u_josh: {
    id: "u_josh",
    name: "Josh Reyes",
    handle: "joshreyes",
    status: "Student",
    university: "OLFU",
    college: "CCS",
    program: "BSCS",
    year: "2nd Year",
    campus: "Antipolo",
    focus: "Backend",
    org: "Dev Guild",
    bio: "Opinionated about frameworks and unapologetic about it.",
    badges: ["Debater"],
  },
  u_tricia: {
    id: "u_tricia",
    name: "Tricia Lim",
    handle: "tricialim",
    status: "Student",
    university: "OLFU",
    college: "CCS",
    program: "BSIT",
    year: "3rd Year",
    campus: "Antipolo",
    focus: "Community",
    org: "Events",
    bio: "If there’s a committee, I’m probably in it.",
    badges: ["Organizer"],
  },
  u_miguel: {
    id: "u_miguel",
    name: "Miguel Santos",
    handle: "miguels",
    status: "Student",
    university: "OLFU",
    college: "CCS",
    program: "BSCS",
    year: "4th Year",
    campus: "Antipolo",
    focus: "Security",
    org: "Hack Club",
    bio: "Hackathons, deadlines, and security rabbit holes.",
    badges: ["Hackathon Mentor"],
  },
};

export const MOCK_POSTS = [
  { id: 1, userId: "u_renz", avatar: "RS", time: "2h ago", content: "Just finished our capstone defense! Three years of blood, sweat and debugging paid off. Shoutout to our adviser Sir Navarro for the guidance 🎓", likes: 47, comments: 12, bookmarked: false, tag: "General" },
  { id: 2, userId: "u_maica", avatar: "MV", time: "4h ago", content: "Anyone else struggling with CMSC 142 finals? The automata theory part is killing me. Study group sa lib mamaya around 6pm? 📚", likes: 23, comments: 31, bookmarked: true, tag: "Academics" },
  { id: 3, userId: "u_josh", avatar: "JR", time: "5h ago", content: "Hot take: Django > Laravel for our school projects. The ORM alone saves so many headaches. Fight me in the comments.", likes: 61, comments: 44, bookmarked: false, tag: "Tech" },
  { id: 4, userId: "u_tricia", avatar: "TL", time: "8h ago", content: "CCS Night 2025 planning committee is looking for volunteers! DM me or drop your name in the comments if you're interested 🎉", likes: 88, comments: 19, bookmarked: false, tag: "Events" },
  { id: 5, userId: "u_miguel", avatar: "MS", time: "1d ago", content: "Reminder that the hackathon registration closes TOMORROW. Team slots are almost full — register at the CCS org office now!", likes: 102, comments: 7, bookmarked: true, tag: "Events" },
];

export const FORUM_RAIL = {
  rising: ["CCS Night 2025 hype thread", "Best IDE for Java?", "Thesis defense tips megathread"],
  interests: ["Who's joining the hackathon?", "CMSC 142 reviewer shared", "Internship openings thread"],
  trending: ["#CCSNight2025", "#ThesisSeason", "#CodeAndCoffee"],
};

